# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c  # even-though its a swift project, if I don't say objective-c I end up with old xcode environment
osx_image: xcode7.2
cache: cocoapods
#podfile: Example/Podfile

before_install:
- rvm install 2.1.5
- gem install cocoapods # Since Travis is not always on latest version
- pip install codecov
# - pod install --project-directory=Example
script:
# - xcrun simctl list
- set -o pipefail && xcodebuild test -project NACommonUtils.xcodeproj -scheme NACommonUtils  -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

after_success:
  - codecov
